theme: jekyll-theme-cayman

title: [日进一步]
description: [不积跬步，无以至千里；不积小流，无以成江海。]

url:              http://rijikuibu.com/
baseurl:          http://rijikuibu.com/

github:
  repo:           https://github.com/paleolake
